DRAPEAUX = {
    "Bahrain": "bh", 
    "Saudi Arabia": "sa", 
    "Australia": "au", 
    "Japan": "jp",
    "China": "cn", 
    "USA": "us", 
    "United States": "us", 
    "Monaco": "mc", 
    "Spain": "es", 
    "Canada": "ca", 
    "Austria": "at", 
    "United Kingdom": "gb",
    "Hungary": "hu", 
    "Belgium": "be", 
    "Netherlands": "nl", 
    "Italy": "it",
    "Azerbaijan": "az", 
    "Singapore": "sg", 
    "Mexico": "mx", 
    "Brazil": "br",
    "Qatar": "qa", 
    "Abu Dhabi": "ae", 
    "France": "fr"
}